import '../styles/MainPage.css';

function PaginaPrincipal() {
    return (
        <div>
            <h1>Bienvenido a Página Kidda</h1>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Natus numquam voluptatem non fugiat facere, vel dolore ducimus aliquam praesentium cum, nesciunt hic laudantium totam odio laboriosam? Quam debitis ratione provident?
            Totam, perspiciatis, accusamus doloribus corporis error molestiae ipsum numquam ab illo obcaecati, reprehenderit repellendus cum autem unde facilis iste odio dolorem. Expedita consequuntur molestias quos delectus corporis. Neque, magnam! Facere.
            Consequuntur animi reiciendis in beatae laudantium quasi totam ipsam earum illum eveniet sapiente voluptatem harum quidem magni, culpa similique veniam error ab asperiores odio. Cupiditate voluptate incidunt id veniam at.
            Eligendi, eos, tempora fuga, ex voluptatum quaerat error molestias cupiditate iure perferendis ab tenetur beatae rerum mollitia? Reprehenderit commodi obcaecati amet deleniti optio? Temporibus non amet quod natus cumque eum?
            Labore accusantium commodi modi quos in praesentium molestias repellendus explicabo, harum, esse impedit exercitationem itaque doloremque, deleniti ipsam? Fuga libero, sunt voluptatem rerum laboriosam eligendi ipsam est nostrum veritatis ex.
            Laborum asperiores exercitationem ipsa sapiente ipsam recusandae at laboriosam, mollitia deserunt? Veritatis id suscipit quae. Laboriosam ipsa vero sequi, eligendi incidunt saepe accusamus, delectus deserunt velit est iste quisquam? Amet.
            Odit adipisci tempore expedita quia dolorum ducimus placeat quae enim omnis doloribus corporis quis nesciunt libero officiis, nihil praesentium accusamus, voluptatem sunt dolor minima? Placeat minus autem reiciendis dolore consequuntur.
            Nobis quae iusto, sit itaque deserunt neque, aliquam quos sed dolores soluta, facere ex modi. Doloribus quibusdam, temporibus, minima earum quisquam sit voluptas aperiam repellat hic quas laborum enim quia!
            Velit voluptatibus animi id aliquid ab obcaecati repudiandae fuga voluptate, sint accusamus sequi consectetur ea nam, autem vero provident. Modi consequatur aliquam doloribus officia amet cupiditate saepe ut cumque praesentium.
            Aut nam voluptatem, sapiente quae est laborum animi doloribus, fugit ab necessitatibus voluptatibus accusantium magnam vel. Quaerat id magni eaque, est numquam officiis debitis neque quos amet quo labore ex.
            Amet perspiciatis quae facere repellendus veritatis iure recusandae incidunt obcaecati accusantium quasi voluptate veniam porro consequuntur, nostrum animi! Quae, eveniet. Sunt deleniti odio aliquam libero numquam laboriosam maxime dolore incidunt.
            Totam nobis officia commodi error voluptatem dicta quo earum repellat similique. Cum ipsa minus assumenda excepturi nostrum consequatur adipisci rerum autem iste pariatur? Nulla, culpa? Placeat veniam explicabo labore repudiandae?
            Ratione nobis minima animi aliquam aspernatur amet velit molestiae nostrum, est dolor cumque saepe in ea sunt pariatur hic distinctio delectus nisi. Deleniti, eveniet! Dolor minus accusantium eligendi temporibus itaque.
            Ipsam sequi, nihil praesentium dolorem optio placeat quas iusto nam expedita necessitatibus, at, aspernatur dolorum amet! Placeat at nobis quaerat similique ad repudiandae ea accusantium ipsum, autem impedit illo dolorem?
            Aliquam tempore harum exercitationem illum placeat sunt! Dolore, sunt porro distinctio, tempore deserunt aliquid doloremque, incidunt dignissimos molestiae earum iste repudiandae placeat. Voluptas, in. Quia incidunt cum unde dolore voluptatum?
            Qui deleniti culpa natus consequuntur, dicta, nihil rerum necessitatibus aliquid ad consequatur voluptatibus eius beatae repellat eum excepturi! Similique nostrum, nihil laboriosam cum aperiam minus error sapiente assumenda. Dolorum, amet.
            Id consectetur eum repellat temporibus eius rerum rem ducimus, similique earum optio, consequuntur veniam? Laudantium, nam nostrum iure corrupti maxime magni reiciendis, fugiat itaque impedit, repudiandae nesciunt est tempora ab?
            Tempora recusandae, facilis magni magnam libero eum quam asperiores ad eos nesciunt neque qui alias ratione quis odit tempore atque sunt cumque sint nisi. Doloremque id incidunt eum doloribus cupiditate.
            Voluptates commodi totam enim, quos reiciendis ipsum sit atque nostrum expedita illum necessitatibus quaerat ratione quia consectetur fugiat eveniet iusto blanditiis maiores magni! Quasi distinctio magnam nostrum, cupiditate provident incidunt.
            Cum doloremque tempore perferendis recusandae nihil corrupti alias numquam maiores dolorum, veritatis temporibus fugiat? Nihil pariatur laudantium eos voluptate explicabo ullam, aliquid iusto excepturi similique quaerat sed dolorum consequuntur inventore.
            Dolorum nam minus alias quibusdam cum, debitis maxime nihil quo, quidem quasi commodi? Fugiat accusantium aliquam sit, officiis architecto similique repellendus autem iure aperiam ratione voluptatem harum porro eligendi aspernatur!
            Deserunt consequuntur quis a, minus error dicta veritatis tempore? Quidem veritatis quae deserunt facilis mollitia hic quisquam dolores facere natus ab. Fugiat animi explicabo facilis, itaque odio quas unde asperiores.
            Reprehenderit, officia qui dicta iste quibusdam voluptate officiis quos unde tempora alias autem consectetur corrupti illum necessitatibus velit aliquid nesciunt est incidunt maxime excepturi? Harum aliquid aspernatur molestias nihil inventore.
            Qui quos hic minima quaerat provident veniam amet sint aliquam maiores. Ut eos voluptatem rem autem assumenda. Quia sequi, quis in, laborum vel at officiis accusamus quibusdam earum ipsum doloribus.
            Iusto recusandae consectetur, labore consequatur blanditiis quod? Dolores ad temporibus, ex, autem in velit quia reprehenderit voluptas corporis enim illum repudiandae adipisci fugit consectetur, natus rerum? Modi officia dolore tempora.
            A soluta eligendi aperiam veritatis ad. Dolore tempore quidem harum voluptatum fuga ut ipsum rem rerum ea ipsa, enim a labore fugit recusandae eaque hic neque dolor facere voluptas perspiciatis.
            Ipsam, hic, ipsum maiores vel accusamus consectetur blanditiis voluptates rerum exercitationem quod at mollitia, consequuntur natus veniam aut nobis pariatur eius amet quidem numquam molestias velit sed architecto! Voluptatum, pariatur!
            Voluptate labore quisquam omnis voluptas accusamus cumque! Nihil nemo vero modi magnam natus, repellendus ut quos et ab unde eius qui enim? Laborum, exercitationem quod! Facere repellendus doloremque iste expedita!
            Corporis incidunt dolore assumenda molestias perferendis? Laboriosam deleniti, commodi eos error fugit obcaecati minus maxime voluptates hic, fuga sit ex omnis veniam blanditiis quasi molestiae laudantium mollitia aliquam iure ab!
            Voluptatum voluptatibus nihil, at accusantium tempora nobis nemo ratione consequatur ipsam dolorum, eum neque possimus? Corporis, minima, magnam voluptatum nihil omnis voluptatem suscipit ipsum praesentium numquam veniam, ipsa recusandae itaque.
            Maiores, eos debitis nesciunt eaque esse, cum sint molestiae eligendi quam ab animi nostrum ipsum incidunt culpa. Natus deleniti sapiente adipisci, reprehenderit, dignissimos voluptas exercitationem dicta fuga at ipsum earum.
            Accusantium, deleniti hic facilis, illo aut sed minus tempora veritatis repudiandae natus nulla a? Odit eius explicabo velit nesciunt suscipit ea excepturi esse quia, nobis magni saepe quisquam culpa harum.
            Fugit maiores ea, aliquid nihil id, mollitia eius voluptate aspernatur laboriosam voluptas fugiat corrupti, aliquam corporis porro tenetur beatae officia neque cumque possimus eligendi in impedit fuga ad. Provident, non?
            In eveniet aliquid iure ut, illo reiciendis. Fuga enim rem eum necessitatibus ratione sed rerum sequi nam, repellat accusamus esse obcaecati amet, eaque ducimus! Maxime voluptatibus alias illum blanditiis placeat!
            Alias corporis quaerat accusantium voluptate quas quam quibusdam molestias dignissimos consectetur in recusandae, odit obcaecati nam blanditiis provident, sapiente commodi! Nobis, consequuntur? Suscipit, soluta repellat. Eos consectetur ullam corporis ex.
            Accusantium eius sed eligendi facere repellat, ducimus minima nemo velit similique sit! Expedita reiciendis placeat eos eveniet rerum deleniti inventore, harum numquam impedit ipsa quo. Assumenda iste molestiae quasi in!
            Quasi velit architecto ducimus, eveniet numquam eos consequuntur facilis voluptas deleniti quod vel sunt. Perferendis sequi assumenda cupiditate quidem maxime corrupti dicta. Eius, repellat et voluptates reprehenderit reiciendis repellendus iure?
            Possimus qui, nostrum assumenda sed accusantium deleniti laborum, aliquam odio illo tempora nobis! Doloribus enim adipisci ea corrupti veniam eius non rerum est explicabo cupiditate! Voluptatum at cum dolor laboriosam!
            Iure quasi placeat dolore? Autem quo ipsam, natus nisi deleniti quam impedit enim, ea modi sapiente voluptatem eos hic odio eaque possimus maxime temporibus maiores, consectetur quisquam. Nesciunt, nam dicta?
            Est sapiente laboriosam commodi corporis debitis dolorem similique praesentium laborum iusto in architecto facere odio corrupti eveniet sed qui blanditiis asperiores officiis dolores doloremque vitae vel, minima neque porro! Provident?
            Voluptatibus id expedita sequi exercitationem, tenetur, odit ipsa, quod ipsum nostrum unde voluptas. Sint maiores molestias iure repellat rem sequi repellendus vero, consequatur et dolor a ducimus, soluta nobis! Sunt?
            Eligendi architecto magnam, itaque quisquam adipisci hic molestias quaerat porro velit, laborum ex illo dolor, asperiores odit facere in aliquid. Dolorum provident possimus aliquid, placeat tenetur qui quos. Explicabo, velit.
            Maxime libero accusamus possimus consequatur commodi doloremque nulla perspiciatis ipsam temporibus, sequi quisquam itaque explicabo ratione neque soluta architecto dolore minima ut optio, inventore officia minus eos quo! Eveniet, id?
            Excepturi, in delectus voluptatibus porro maiores quod autem ratione explicabo, eius libero maxime minus illum nam aliquid sint blanditiis corporis ullam! Aliquid ea tempore at quia vel mollitia repellat quidem.
            Voluptatibus quam quaerat aut cupiditate! Quas voluptate explicabo odit sunt error praesentium eligendi, suscipit maxime harum quia eum ipsum omnis voluptatibus tempore rem possimus ad odio cumque exercitationem voluptates? Cupiditate!
            Veniam consequatur eligendi enim repudiandae distinctio quidem possimus pariatur soluta iste deserunt magni ad officia tempore molestias modi atque nemo nihil a consequuntur, sapiente exercitationem aliquid! Sapiente, magni velit? Laudantium.
            Natus nulla sapiente quas quae dignissimos atque facilis quam eius doloremque, omnis at repellendus sint provident, officia distinctio autem maiores exercitationem dolorum, corporis impedit tempore? Eveniet vitae sapiente eaque laboriosam.
            Deleniti dolorum suscipit enim eum earum vero repellendus rerum distinctio eos odit perferendis sint debitis dolor iste ex, tempora est voluptatem optio unde praesentium tempore voluptatibus, magni quam! Laboriosam, labore.
            Magnam, aspernatur. Ipsum beatae voluptatibus ipsa vitae laudantium cum obcaecati! Culpa dolorem dignissimos eos beatae voluptatibus, nemo laudantium maxime expedita atque ex architecto enim blanditiis cum asperiores vel iusto et?
            Impedit distinctio vel molestiae nesciunt? Illum aperiam, voluptas libero accusamus expedita vero esse aut, numquam facilis quibusdam rerum, necessitatibus eos consequuntur corrupti perferendis commodi neque consequatur unde? Corporis, reprehenderit dolorem!</p>
        </div>
    );
}

export default PaginaPrincipal;